/* API SISTEMA COLEGIO.
 *
 * 
 *
 * Codigo Basado en Pedro Gatica , Kimberly Soazo , Joaquin Valenzuela 
 *
 * 
 *
 * Este programa es software libre; Puedes redistribuirlo y / o modificarlo.
 * bajo los términos de la Licencia Pública General de GNU tal como fue publicada por
 * la Fundación de Software Libre; ya sea la versión 2 de la Licencia, o
 * (a su elección) cualquier versión posterior.
 *
 * ------------------------------------------------- ----------------------------
 * Copyright (c) 2019,Pedro Gatica , Joaquin Valenzuela,Kimberly Soazo
 * Todos los derechos reservados.
 *
 * CONDICIONES DE LA LICENCIA
 *
 * La distribución gratuita y el uso de este software tanto en origen como en binario.
 * Se permite el formulario (con o sin cambios) siempre que:
 *
 * 1. Las distribuciones de este código fuente incluyen el copyright anterior.
 * Aviso, esta lista de condiciones y el siguiente descargo de responsabilidad;
 *
 * 2. Las distribuciones en formato binario incluyen el copyright anterior.
 * Aviso, esta lista de condiciones y el siguiente aviso legal.
 * en la documentación y / u otros materiales asociados;
 *
 * 3. el nombre de los titulares de los derechos de autor no se utiliza para promocionar productos
 * construido utilizando este software sin permiso escrito específico.
 *
 * ALTERNATIVAMENTE, siempre que este aviso se mantenga en su totalidad, este producto
 * se puede distribuir según los términos de la Licencia Pública General de GNU (GPL),
 * en cuyo caso, las disposiciones de la GPL se aplican EN LUGAR DE las mencionadas anteriormente.
 *
 * DESCARGO DE RESPONSABILIDAD
 *
 * Este software se proporciona "tal cual" sin garantías explícitas ni implícitas
 * con respecto a sus propiedades, incluida, entre otras, la corrección
 * y / o aptitud para el propósito.
 * ------------------------------------------------- ----------------------------
 * /

*/

package vista;

import controlador.Ctrl_ElminarAlumno;
import controlador.Ctrl_Ingresar_Alumno;
import controlador.Ctrl_Modificar_Alumno;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import vista.Panel_Admin;

/**
 *
 * @author kimbe
 */
public class Ingresar_Alum extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar_Alumno
     */
    public Ingresar_Alum() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setIconImage(new ImageIcon(getClass().getResource(
                "/imagenes/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtModAlumn = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Seleccionar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datosalumno = new javax.swing.JLabel();
        rut = new javax.swing.JLabel();
        txtrutalumno = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        txtnombrealumno = new javax.swing.JTextField();
        lblapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        fechanac = new javax.swing.JLabel();
        txtfechanacimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        datosapoderado = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        txtrutapo = new javax.swing.JTextField();
        nombrea = new javax.swing.JLabel();
        txtnombreapoderado = new javax.swing.JTextField();
        parentesco = new javax.swing.JLabel();
        txtparentesco = new javax.swing.JTextField();
        contacto = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEstadoMatricula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaMatricula = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnBorrarAlumno = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rut1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        lblapellido1 = new javax.swing.JLabel();
        fechanac1 = new javax.swing.JLabel();
        datosalumno1 = new javax.swing.JLabel();
        datosapoderado1 = new javax.swing.JLabel();
        ruta1 = new javax.swing.JLabel();
        nombrea1 = new javax.swing.JLabel();
        parentesco1 = new javax.swing.JLabel();
        contacto1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMfenac = new javax.swing.JTextField();
        txtMrut = new javax.swing.JTextField();
        txtMnombre = new javax.swing.JTextField();
        txtMapelldio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMrutA = new javax.swing.JTextField();
        txtMnomA = new javax.swing.JTextField();
        txtMparenA = new javax.swing.JTextField();
        txtMconA = new javax.swing.JTextField();
        txtMdirA = new javax.swing.JTextField();
        txtMestM = new javax.swing.JTextField();
        txtMfecM = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtModificarAlumn = new javax.swing.JTable();
        btnVerAlumn = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tbtModAlumn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtModAlumn);

        jLabel11.setText("jLabel11");

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Seleccionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Ingresar Nuevo Alumno");

        datosalumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        datosalumno.setText("Datos del Alumno:");
        datosalumno.setToolTipText("");

        rut.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rut.setText("Rut:");

        txtrutalumno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombre.setText("Nombre:");

        txtnombrealumno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        lblapellido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblapellido.setText("Apellido:");

        txtapellido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        fechanac.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fechanac.setText("Fecha Nacimiento: ");

        txtfechanacimiento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Contraseña:");

        datosapoderado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        datosapoderado.setText("Datos del Apoderado:");

        ruta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ruta.setText("Rut Apoderado:");

        txtrutapo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        nombrea.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombrea.setText("Nombre Apoderado:");

        txtnombreapoderado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        parentesco.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        parentesco.setText("Parentesco:");

        txtparentesco.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        contacto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contacto.setText("Contacto:");

        txtcontacto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Dirección:");

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Estado de Matricula");

        jLabel4.setText("Datos de la matricula :");

        jLabel7.setText("Fecha Matricula");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEstadoMatricula)
                    .addComponent(txtFechaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEstadoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        btnguardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnBorrarAlumno.setText("Borrar");
        btnBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAlumnoActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datosalumno)
                                    .addComponent(jLabel1)
                                    .addComponent(datosapoderado)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombre)
                                            .addComponent(rut))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtrutalumno, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                            .addComponent(txtnombrealumno)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblapellido)
                                            .addComponent(fechanac)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtfechanacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                            .addComponent(txtclave)
                                            .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(68, 68, 68)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ruta)
                                .addGap(32, 32, 32)
                                .addComponent(txtrutapo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrea)
                                    .addComponent(parentesco)
                                    .addComponent(contacto)
                                    .addComponent(jLabel2)
                                    .addComponent(btnguardar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombreapoderado)
                                    .addComponent(txtparentesco)
                                    .addComponent(txtcontacto)
                                    .addComponent(txtDireccion)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnBorrarAlumno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnlimpiar)))))
                        .addGap(74, 74, 74)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnvolver)))
                .addGap(202, 202, 202))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(datosalumno)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rut)
                    .addComponent(txtrutalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(txtnombrealumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellido))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechanac)
                            .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(datosapoderado)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ruta)
                            .addComponent(txtrutapo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrea)
                    .addComponent(txtnombreapoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentesco)
                    .addComponent(txtparentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacto)
                    .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnBorrarAlumno)
                    .addComponent(btnlimpiar)
                    .addComponent(btnvolver))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Ingreso Alumno", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        rut1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rut1.setText("Rut:");

        nombre1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombre1.setText("Nombre:");

        lblapellido1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblapellido1.setText("Apellido:");

        fechanac1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fechanac1.setText("Fecha Nacimiento: ");

        datosalumno1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        datosalumno1.setText("Datos del Alumno:");
        datosalumno1.setToolTipText("");

        datosapoderado1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        datosapoderado1.setText("Datos del Apoderado:");

        ruta1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ruta1.setText("Rut Apoderado:");

        nombrea1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombrea1.setText("Nombre Apoderado:");

        parentesco1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        parentesco1.setText("Parentesco:");

        contacto1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contacto1.setText("Contacto:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Dirección:");

        jLabel10.setText("Estado de Matricula: ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Datos de la matricula :");

        jLabel12.setText("Fecha Matricula");

        tbtModificarAlumn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbtModificarAlumn.setComponentPopupMenu(jPopupMenu1);
        tbtModificarAlumn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbtModificarAlumnAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tbtModificarAlumn);

        btnVerAlumn.setText("VER");
        btnVerAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumnActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechanac1)
                            .addComponent(rut1)
                            .addComponent(nombre1)
                            .addComponent(lblapellido1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMfenac)
                            .addComponent(txtMnombre)
                            .addComponent(txtMapelldio)
                            .addComponent(txtMrut, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosapoderado1)
                            .addComponent(datosalumno1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMfecM, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(125, 125, 125)
                                            .addComponent(txtMrutA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nombrea1)
                                                .addComponent(parentesco1)
                                                .addComponent(contacto1)
                                                .addComponent(jLabel9)
                                                .addComponent(ruta1))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtMparenA)
                                                        .addComponent(txtMconA)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                            .addGap(0, 0, Short.MAX_VALUE)
                                                            .addComponent(txtMnomA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtMdirA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(5, 5, 5))))
                                        .addComponent(jLabel5)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMestM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnVerAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(datosalumno1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rut1)
                            .addComponent(txtMrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre1)
                            .addComponent(txtMnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellido1)
                            .addComponent(txtMapelldio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechanac1)
                            .addComponent(txtMfenac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(datosapoderado1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ruta1)
                            .addComponent(txtMrutA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrea1)
                            .addComponent(txtMnomA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parentesco1)
                            .addComponent(txtMparenA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contacto1)
                            .addComponent(txtMconA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtMdirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMestM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMfecM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnVerAlumn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Alumno", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        dispose();
        Panel_Admin mostrar = new Panel_Admin();
        mostrar.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        
        txtrutalumno.setText(null);
        txtnombrealumno.setText(null);
        txtfechanacimiento.setText(null);
        
        txtDireccion.setText(null);
        txtnombreapoderado.setText(null);
        txtparentesco.setText(null);
        txtcontacto.setText(null);
        txtapellido.setText(null);
        txtclave.setText(null);

        

        //txtNmatricula.setText(null);

        txtEstadoMatricula.setText(null);
        txtFechaMatricula.setText(null);
        
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        
        Ctrl_Ingresar_Alumno ver = new Ctrl_Ingresar_Alumno();
        
        String rutalumno = txtrutalumno.getText();
        String nombrealumno = txtnombrealumno.getText();
        String apellidoalumno = txtapellido.getText();
        String fechanacimiento = txtfechanacimiento.getText();
        String clave = txtclave.getText();
        
        String rutapoderado = txtrutapo.getText();
        String nombreapoderado = txtnombreapoderado.getText();
        String parentesco = txtparentesco.getText();
        int contacto = Integer.parseInt(txtcontacto.getText());
        String direccion = txtDireccion.getText();

        //Matricula

        //int numMatricula = Integer.parseInt(txtNmatricula.getText());

        String estadoMatricula = txtEstadoMatricula.getText();
        String fecha = txtFechaMatricula.getText();
        
        ver.IngresarAlumno(rutalumno, nombrealumno, apellidoalumno, fechanacimiento,
                clave, rutapoderado, nombreapoderado, parentesco, contacto, direccion);
        

        ver.IngresarMatricula(estadoMatricula, fecha, rutalumno);

        //ver.IngresarMatricula(numMatricula, estadoMatricula, fecha, rutalumno);

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Ctrl_ElminarAlumno ver = new Ctrl_ElminarAlumno();
        
        String rutAlumno = JOptionPane.showInputDialog("Ingrese el rut del alumno que desea eliminar");
        
        ver.EliminarAlumno(rutAlumno);
        ver.EliminarMatricula(rutAlumno);
    }                                                                                              


    private void tbtModificarAlumnAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbtModificarAlumnAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtModificarAlumnAncestorMoved

    private void btnVerAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnActionPerformed
        Ctrl_Modificar_Alumno ver = new Ctrl_Modificar_Alumno();
        
        ver.DatosAlumn(tbtModificarAlumn);
    }//GEN-LAST:event_btnVerAlumnActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        int fila = tbtModificarAlumn.getSelectedRow();
        if (fila>=0) {
            txtMrut.setText(tbtModificarAlumn.getValueAt(fila, 0).toString());
            txtMnombre.setText(tbtModificarAlumn.getValueAt(fila, 1).toString());
            txtMapelldio.setText(tbtModificarAlumn.getValueAt(fila, 2).toString());
            txtMfenac.setText(tbtModificarAlumn.getValueAt(fila, 3).toString());
            txtMrutA.setText(tbtModificarAlumn.getValueAt(fila, 4).toString());
            txtMnomA.setText(tbtModificarAlumn.getValueAt(fila, 5).toString());
            txtMparenA.setText(tbtModificarAlumn.getValueAt(fila, 6).toString());
            txtMconA.setText(tbtModificarAlumn.getValueAt(fila, 7).toString());
            txtMdirA.setText(tbtModificarAlumn.getValueAt(fila, 8).toString());
            txtMestM.setText(tbtModificarAlumn.getValueAt(fila, 9).toString());
            txtMfecM.setText(tbtModificarAlumn.getValueAt(fila, 10).toString());
            
        }else{
            JOptionPane.showMessageDialog(null, "No selecciono Fila");
        }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Ctrl_Modificar_Alumno ver = new Ctrl_Modificar_Alumno();
        
        
        String Modrut = txtMrut.getText();
        String Modnombre= txtMnombre.getText();
        String Modapellido = txtMapelldio.getText();
        String Modfecnac = txtMfenac.getText();
        String Modruta = txtMrutA.getText();
        String ModnomA= txtMnomA.getText();
        String ModparenA = txtMparenA.getText();
        int ModconA = Integer.parseInt(txtMconA.getText());
        String Moddir = txtMdirA.getText();
        String ModestaM = txtMestM.getText();
        String ModFecM = txtMfecM.getText();
        
        ver.ModificarAlumn(Modrut, Modnombre, Modapellido, Modfecnac, Modruta, ModnomA, ModparenA, ModconA, Moddir);
        ver.ModificarMatricula(Modrut, ModestaM, ModFecM);
    }                                                                                        


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Alum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Alum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Alum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Alum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Alum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Seleccionar;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btnBorrarAlumno;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVerAlumn;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel contacto1;
    private javax.swing.JLabel datosalumno;
    private javax.swing.JLabel datosalumno1;
    private javax.swing.JLabel datosapoderado;
    private javax.swing.JLabel datosapoderado1;
    private javax.swing.JLabel fechanac;
    private javax.swing.JLabel fechanac1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblapellido1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombrea;
    private javax.swing.JLabel nombrea1;
    private javax.swing.JLabel parentesco;
    private javax.swing.JLabel parentesco1;
    private javax.swing.JLabel rut;
    private javax.swing.JLabel rut1;
    private javax.swing.JLabel ruta;
    private javax.swing.JLabel ruta1;
    private javax.swing.JTable tbtModAlumn;
    private javax.swing.JTable tbtModificarAlumn;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoMatricula;
    private javax.swing.JTextField txtFechaMatricula;
    private javax.swing.JTextField txtMapelldio;
    private javax.swing.JTextField txtMconA;
    private javax.swing.JTextField txtMdirA;
    private javax.swing.JTextField txtMestM;
    private javax.swing.JTextField txtMfecM;
    private javax.swing.JTextField txtMfenac;
    private javax.swing.JTextField txtMnomA;
    private javax.swing.JTextField txtMnombre;
    private javax.swing.JTextField txtMparenA;
    private javax.swing.JTextField txtMrut;
    private javax.swing.JTextField txtMrutA;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtcontacto;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtnombrealumno;
    private javax.swing.JTextField txtnombreapoderado;
    private javax.swing.JTextField txtparentesco;
    private javax.swing.JTextField txtrutalumno;
    private javax.swing.JTextField txtrutapo;
    // End of variables declaration//GEN-END:variables
}
